[package]
name = "day08"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
edition = "2018"

[dependencies]
aoc2020 = { path = ".." }
bitvec = "0.19.6"
color-eyre = "0.5.11"
parse-display = "0.4.1"
structopt = "0.3.26"
thiserror = "1.0.63"
